name: sponsorbrein
favicon: null
layout_spectrum: 0.51526
typography_spectrum: 0.6641145199537277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#664992'
    - '#000000'
    - '#dd002c'
    - '#3196bd'
  brandStrength: 0.34418024169281125
  lightness: 0.3359980678651482
  saturation: 0.518386194948107
  rhythmicContrast: 0.25
purpose: []
